apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: ensure-images-from-trusted-registry
  namespace: default
spec:
  validationFailureAction: Enforce
  rules:
  - name: trusted-registry
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Todas as imagens devem ser provenientes de um registro confiável."
      pattern:
        spec:
          containers:
          - name: "*"
            image: "cgr.dev/chainguard/*"