apiVersion: v1
kind: Pod
metadata:
  labels:
    run: server
    service: webserver
  name: server
spec:
  containers:
  - image: nginx 
    name: webserver
    volumeMounts:
    - mountPath: /server
      name: volume-emptydir
    resources: 
      limits: 
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  - image: ubuntu
    name: ubuntu
    args: 
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: volume-emptydir
    emptyDir:
      sizeLimit: "256Mi"

