apiVersion: v1
kind: Pod
metadata:
  labels:
    run: server
    service: webserver
  name: server
spec:
  containers:
  - image: ubuntu 
    name: ubuntu
    resources: 
      limits: 
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
    args: 
    - sleep
    - "1800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
