apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: ehclaro-pvc
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ehclaro-pvc
    persistentVolumeClaim:
      claimName: ehclaro-pvc
  restartPolicy: OnFailure