apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: ehclaro
  name: ehclaro-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /mnt/data
  storageClassName: ehclaro