---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: server
  name: server
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: server 
  labels:
    app: server
spec:
  replicas: 3 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2 
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.66
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: 
          limits:
            cpu: "0.2"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10 
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:80/
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
      - name: bind9
        image: ubuntu/bind9:edge
        env:
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP

