apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-servico
  namespace: producao 
  labels:
    app: meu-servico
spec:
  replicas: 3 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: meu-servico
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: meu-servico
        version: "v2-problematica"
    spec:
      containers:
      - name: meu-servico-container
        image: linuxtips/memory-eater:0.2
        resources: 
          limits:
            memory: "48Mi"
            cpu: 0.5
          requests:
            memory: "64Mi"
            cpu: 0.3
        startupProbe:
          httpGet:
            path: /startupz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 3
          failureThreshold: 10 
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 3
        readnessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

