apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.106/32 # single ip address
  - 10.10.0.0/16 # range of ip addresses cluster internal