apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: hostPath
  name: local-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath: 
    path: /mnt/data