apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-faminto 
    service: stress 
  name: pod-faminto 
  namespace: treinamento-ch2 
spec:
  containers:
  - image: polinux/stress 
    name: stress
    resources: 
      limits: 
        cpu: "0.5"
        memory: "200Mi"
      requests:
        cpu: "0.3"
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","250M","--vm-hang","1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
