apiVersion: v1
kind: Pod 
metadata:
  name: pod-secret
spec:
  containers:
  - name: app
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: ehclaro-test
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: ehclaro-test
          key: password